// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://macvfnhieudxquthpqrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hY3ZmbmhpZXVkeHF1dGhwcXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNjA5MTYsImV4cCI6MjA2NzgzNjkxNn0.r_ifFYsWFk2F826xz55Zb7tO5m0iGkir_00fWLuQbyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});